apiVersion: apps/v1
kind: Deployment 
metadata:
  name: traffic
spec:
  replicas: 10
  selector:
    matchLabels:
      app: linux
  template:
    metadata:
      labels:
        app: linux
    spec:
      containers:
      - name: 
        image: 
        command: 
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
